//
//  HomeRouter.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  func showLaunchPage(index: Int)
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
    func showLaunchPage(index: Int) {
        let launch = dataStore?.launches?[index]
        // TODO pass launch to laundetail vc
    }

  // MARK: Navigation
  
  func navigateToLaunchPage(source: HomeViewController, destination: UIViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
//  func passDataToLaunchPage(source: HomeDataStore, destination: inout LaunchDataStore) {
//    destination.launch = source.name
//  }
}
