//
//  HomePresenter.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
  func presentSomething(response: Home.FetchHomeLaunches.Response)
}

class HomePresenter: HomePresentationLogic {
  weak var viewController: HomeDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Home.FetchHomeLaunches.Response) {
    let viewModel = Home.FetchHomeLaunches.ViewModel()
    viewController?.displayHomeLaunches(viewModel: viewModel)
  }
}
