//
//  HomeModels.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Home {
    
  // MARK: Fetch the informations on space x launches
  
  enum FetchHomeLaunches {
    struct Request {
    }
    
    struct Response {
        var launches: [Launch]?
        var error: Error?
    }
    
    struct ViewModel {
        struct DisplayedLaunch {
            var name: String?
            var date: String
            var imgUrl: String?
        }
        var displayedLaunches: [DisplayedLaunch]
        var error: Error?
    }
  }
}
