//
//  HomeViewController.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit
import SnapKit
import SkeletonView

protocol HomeDisplayLogic: class {
    func displayHomeLaunches(viewModel: Home.FetchHomeLaunches.ViewModel)
    func displayHomeSortedLaunches(viewModel: Home.FetchHomeLaunches.ViewModel)
   
}

final class HomeViewController: UIViewController, HomeDisplayLogic {
    var interactor: HomeBusinessLogic?
    var router: (NSObjectProtocol & HomeRoutingLogic & HomeDataPassing)?
    
    // MARK: Outlets
    
    lazy var collectionView: UICollectionView = {
        let cv = UICollectionView(frame: .zero, collectionViewLayout: flowLayout)
        cv.backgroundColor = UIColor.white
        cv.dataSource = self
        cv.delegate = self
        return cv
    }()
    
    lazy private var flowLayout: UICollectionViewFlowLayout = {
        let layout = UICollectionViewFlowLayout()
        layout.minimumInteritemSpacing = Style.Size.margin
        layout.minimumLineSpacing = Style.Size.margin
        layout.sectionInset = UIEdgeInsets(top: 0, left: Style.Size.margin, bottom: 0.0, right: Style.Size.margin)
        return layout
    }()
    
    lazy var refresher: UIRefreshControl = {
        let refreshControl = UIRefreshControl()
        refreshControl.tintColor = .black
        refreshControl.addTarget(self, action: #selector(fetchHomeLaunches), for: .valueChanged)
        return refreshControl
    }()
    
    lazy var searchController: UISearchController = {
        var controller = UISearchController(searchResultsController: nil)
        controller.searchResultsUpdater = self
        controller.obscuresBackgroundDuringPresentation = false
        controller.searchBar.tintColor = .white
        controller.searchBar.placeholder = "Search Launches"
        controller.searchBar.searchBarStyle = .minimal
        return controller
    }()
    
    let segmentedControl = UISegmentedControl(items: ["Past Launches", "Upcoming Launches"])
    
    // MARK: Variables
    
    private var collectionViewSizeChanged: Bool = false
    var displayedLaunches: [Home.FetchHomeLaunches.ViewModel.DisplayedLaunch] = []
  
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = HomeInteractor()
        let presenter = HomePresenter()
        let router = HomeRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setUpUI() {
        view.isSkeletonable = true
        let nav = self.navigationController?.navigationBar
        nav?.barStyle = UIBarStyle.black
        nav?.isTranslucent = false
        nav?.tintColor = UIColor.white
        nav?.titleTextAttributes = [NSAttributedString.Key.foregroundColor: UIColor.white]
        self.navigationItem.title = "Home To Space X Launches"
        self.navigationItem.searchController = searchController
        view.backgroundColor = .white
        definesPresentationContext = true
        setupSegmentedControl()
        setupCollectionView()
    }
    
    private func setupSegmentedControl() {
        segmentedControl.tintColor = .black
        view.addSubview(segmentedControl)
        segmentedControl.addTarget(self, action: #selector(fetchSortedLaunches), for: .valueChanged)
        segmentedControl.snp.updateConstraints { (make) in
            make.top.equalTo(self.view.safeAreaLayoutGuide.snp.top).offset(10)
            make.width.equalToSuperview().offset(-30)
            make.centerX.equalToSuperview()
        }
        segmentedControl.selectedSegmentIndex = 0
    }
    
    private func setupCollectionView() {
        view.addSubview(collectionView)
        collectionView.snp.updateConstraints { (make) in
            make.top.equalTo(segmentedControl.snp.bottom).offset(10)
            make.left.bottom.right.equalToSuperview()
        }
        collectionView.isSkeletonable = true
        collectionView.backgroundColor = .clear
        collectionView.register(UINib(nibName: "HomeCollectionViewCell", bundle: nil), forCellWithReuseIdentifier: "HomeCollectionViewCell")
    }
    
    private func setRefreshControl() {
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.refresher.endRefreshing()
        }
        guard collectionView.refreshControl == nil else { return }
        collectionView.refreshControl = refresher
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setUpUI()
        fetchHomeLaunches()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        if displayedLaunches.isEmpty {
            collectionView.prepareSkeleton(completion: { _ in
                self.view.showAnimatedGradientSkeleton()
            })
        }
    }
    
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        super.viewWillTransition(to: size, with: coordinator)
        
        collectionViewSizeChanged = true
    }
    
    override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        
        if collectionViewSizeChanged {
            collectionView.collectionViewLayout.invalidateLayout()
        }
    }
    
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        
        if collectionViewSizeChanged {
            collectionViewSizeChanged = false
            collectionView.performBatchUpdates({}, completion: nil)
        }
    }

    // MARK: Fetch the data to display in the home collection view
    
    @objc func fetchHomeLaunches() {
        let request = Home.FetchHomeLaunches.Request(type: segmentedControl.selectedSegmentIndex)
        interactor?.fetchHomeLaunches(request: request)
    }
    
    func displayHomeLaunches(viewModel: Home.FetchHomeLaunches.ViewModel) {
        view.hideSkeleton()
        setRefreshControl()
        setUpLaunchesDisplay(viewModel: viewModel)
    }
    
    // MARK: Sets the type of launches to display
    
    @objc func fetchSortedLaunches(segment: UISegmentedControl) {
        let request = Home.FetchHomeLaunches.Request(type: segmentedControl.selectedSegmentIndex)
        interactor?.fetchHomeSortedLaunches(request: request)
    }
    
    func displayHomeSortedLaunches(viewModel: Home.FetchHomeLaunches.ViewModel) {
        setRefreshControl()
        setUpLaunchesDisplay(viewModel: viewModel)
        if !displayedLaunches.isEmpty {
            collectionView.scrollToItem(at: IndexPath(row: 0, section: 0), at: .top, animated: false)
        }
    }
    
    private func setUpLaunchesDisplay(viewModel: Home.FetchHomeLaunches.ViewModel) {
        guard viewModel.error == nil else {
            Alert.showUnableToRetrieveDataAlert(on: self)
            return
        }
        displayedLaunches = viewModel.displayedLaunches
        collectionView.reloadData()
    }
    
}

// MARK: Collection view delegates

extension HomeViewController: UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout {
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return displayedLaunches.count
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        guard let cell = collectionView.dequeueReusableCell(withReuseIdentifier: "HomeCollectionViewCell", for: indexPath) as? HomeCollectionViewCell, !displayedLaunches.isEmpty else {
            return UICollectionViewCell()
        }
        let launch = self.displayedLaunches[indexPath.row]
        cell.update(item: launch)
        
        return cell
    }
    
    func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAt indexPath: IndexPath) -> CGSize {
        let size: CGFloat
        
        if traitCollection.userInterfaceIdiom == .phone {
            size = floor((collectionView.frame.size.width - 3.0 * Style.Size.margin) / 2.0)
        } else {
            if UIApplication.shared.statusBarOrientation.isLandscape {
                size = floor((collectionView.frame.size.width - 6.0 * Style.Size.margin) / 5.0)
            } else {
                size = floor((collectionView.frame.size.width - 4.0 * Style.Size.margin) / 3.0)
            }
        }
        
        return CGSize(width: size, height: size)
    }
    
    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
        router?.showLaunchPage(index: indexPath.row)
    }
}

// MARK: - SkeletonCollectionViewDataSource

extension HomeViewController: SkeletonCollectionViewDataSource {
    func collectionSkeletonView(_ skeletonView: UICollectionView, cellIdentifierForItemAt indexPath: IndexPath) -> ReusableCellIdentifier {
        return "HomeCollectionViewCell"
    }
    
    func collectionSkeletonView(_ skeletonView: UICollectionView, numberOfItemsInSection section: Int) -> Int {
        return 15
    }
}

// MARK: - Search bar functionnality

extension HomeViewController: UISearchResultsUpdating {
    
    func updateSearchResults(for searchController: UISearchController) {
        let request = Home.SearchLaunches.Request(searchWord: searchController.searchBar.text ?? "")
        interactor?.fetchSearchLaunches(request: request)
    }
}
