//
//  HomeInteractor.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import PromiseKit

protocol HomeBusinessLogic {
    func fetchHomeLaunches(request: Home.FetchHomeLaunches.Request)
}

protocol HomeDataStore {
    var launches: [Launch]? { get }
}

final class HomeInteractor: HomeBusinessLogic, HomeDataStore {
    
    var presenter: HomePresentationLogic?
    var worker = HomeWorker()
    var launches: [Launch]?
    
    // MARK: Fetches the launches from space x api
    
    func fetchHomeLaunches(request: Home.FetchHomeLaunches.Request) {
        
        var response: Home.FetchHomeLaunches.Response!
        
        firstly {
            worker.launchesDataManager.getLaunches()
        }.done { launches in
            self.launches = launches
            response = Home.FetchHomeLaunches.Response(launches: launches, error: nil)
        }.catch { error in
            response = Home.FetchHomeLaunches.Response(launches: nil, error: error)
        }.finally {
            self.presenter?.presentFetchHomeData(response: response)
        }
    }
}
