//
//  HomeRouter.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  func showLaunchPage(index: Int)
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

final class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
    func showLaunchPage(index: Int) {
        guard let launch = dataStore?.filteredLaunches?[index] else { return }
            guard let destinationVC = viewController?.navigationController?.viewControllers.first(where: { $0 is LaunchViewController }) as? LaunchViewController
                else {
                    // Show order not in stack so push fresh
                    let destinationVC = LaunchViewController(nibName: "LaunchViewController", bundle: nil)
                    var destinationDS = destinationVC.router!.dataStore!
                    self.passDataToLaunchPage(source: launch, destination: &destinationDS)
                    viewController!.navigationController?.pushViewController(destinationVC, animated: true)
                    return
            }
            var destinationDS = destinationVC.router!.dataStore!
            passDataToLaunchPage(source: launch, destination: &destinationDS)
            navigateToLaunchPage(source: viewController!, destination: destinationVC)
    }

  // MARK: Navigation
  
  func navigateToLaunchPage(source: HomeViewController, destination: LaunchViewController) {
    source.navigationController?.popToViewController(destination, animated: true)
  }
  
  // MARK: Passing data
  
  func passDataToLaunchPage(source: Launch, destination: inout LaunchDataStore) {
    destination.launch = source
  }
}
