//
//  HomeRouter.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol HomeRoutingLogic {
  func showLaunchPage(index: Int)
}

protocol HomeDataPassing {
  var dataStore: HomeDataStore? { get }
}

class HomeRouter: NSObject, HomeRoutingLogic, HomeDataPassing {
  weak var viewController: HomeViewController?
  var dataStore: HomeDataStore?
  
  // MARK: Routing
  
    func showLaunchPage(index: Int) {
        let launch = dataStore?.launches?[index]
        print(launch)
    }
    
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: HomeViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
//  func passDataToSomewhere(source: HomeDataStore, destination: inout SomewhereDataStore)
//  {
//    destination.name = source.name
//  }
}


//
//func routeToCreateUser() {
//    guard let destinationVC = viewController?.navigationController?.viewControllers.first(where: { $0 is CreateUserViewController }) as? CreateUserViewController
//        else {
//            // Show order not in stack so push fresh
//            let destinationVC = CreateUserViewController(nibName: "CreateUserViewController", bundle: nil)
//            var destinationDS = destinationVC.router!.dataStore!
//            self.passDataToCreateUser(source: self.dataStore!, destination: &destinationDS)
//            viewController!.navigationController?.pushViewController(destinationVC, animated: true)
//            return
//    }
//    var destinationDS = destinationVC.router!.dataStore!
//    passDataToCreateUser(source: dataStore!, destination: &destinationDS)
//    navigateToCreateUser(source: viewController!, destination: destinationVC)
//}
//}
//
//// MARK: Navigation
//
//extension AccountRouter {
//    func navigateToCreateUser(source: AccountViewController, destination: CreateUserViewController) {
//        source.navigationController?.popToViewController(destination, animated: true)
//    }
//}
//
//// MARK: Passing data
//
//extension AccountRouter {
//    func passDataToCreateUser(source: AccountDataStore, destination: inout CreateUserDataStore) {
//        destination.userToEdit = source.user
//    }
//}
