//
//  HomeInteractorTests.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 19/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SpaceOdyssey
import XCTest

class HomeInteractorTests: XCTestCase {
  // MARK: Subject under test
  
  var sut: HomeInteractor!
  
  // MARK: Test lifecycle
  
  override func setUp() {
    super.setUp()
    setupHomeInteractor()
  }
  
  override func tearDown() {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupHomeInteractor() {
    sut = HomeInteractor()
  }
  
  // MARK: Test doubles
  
  class HomePresentationLogicSpy: HomePresentationLogic {
    var presentSomethingCalled = false
    
    func presentSomething(response: Home.Something.Response) {
      presentSomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testDoSomething() {
    // Given
    let spy = HomePresentationLogicSpy()
    sut.presenter = spy
    let request = Home.Something.Request()
    
    // When
    sut.doSomething(request: request)
    
    // Then
    XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
  }
}
