//
//  LaunchPresenter.swift
//  SpaceOdyssey
//
//  Created by Martin Lukacs on 23/09/2018.
//  Copyright (c) 2018 martin. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LaunchPresentationLogic {
  func presentLaunch(response: LaunchPage.GetLaunch.Response)
}

class LaunchPresenter: LaunchPresentationLogic {
  weak var viewController: LaunchDisplayLogic?
  
  // MARK: Do something
  
  func presentLaunch(response: LaunchPage.GetLaunch.Response) {
    let launch = response.launch
    
    let date = (launch.launchDateUTC ?? "").fromUTCToLocalDateTime()
    let title = launch.missionName ?? ""
    let success = launch.launchSuccess ?? false
    let description = launch.details ?? ""
    let videoUrl = launch.links?.youTubeVideoId
    let imgUrl = launch.links?.flickrImages
    let displayedLaunch = LaunchPage.GetLaunch.ViewModel.DisplayedLaunch(title: title, date: date, description: description, success: success, videoUrl: videoUrl, imgUrls: imgUrl)
    
    let viewModel = LaunchPage.GetLaunch.ViewModel(displayedLaunch: displayedLaunch)
    viewController?.displayLaunch(viewModel: viewModel)
  }
}
